### ISSUE TITLE
May need simple edition to install script for minimal debian installs

### ISSUE THREAD

**Issue by piepieninja** [anders-dc/vsfm-linux-x86_64#2]
When running the `./visualsfm.sh` step in your readme I received:

`/bin/sh: 1: unzip: not found`

Of course I simply `sudo apt-get install unzip` and I'm fine, just thought I would notify you that some minimal Debian 8 installs may not come with unzip. Best installer we've found for VSFM.

**Comment by anders-dc** [comment]
Thanks for bringing this to my attention Caleb, I'll get right on it.
